<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="USHYDPABTTA01" failures="1" tests="5" name="Personal loan" time="0.06" errors="0" timestamp="2024-09-09T18:29:25 IST">
  <testcase classname="testNG.day1" name="Demo" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.day1.Demo(day1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="testNG.day2" name="ploan" time="0.001"/>
  <testcase classname="testNG.day4" name="LoginAPIHomeLoan" time="0.001"/>
  <testcase classname="testNG.day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="testNG.day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="testNG.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
